-- Create profiles table
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  constraint username_length check (char_length(username) >= 3)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create packages table
create table packages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  tracking text not null,
  content text not null,
  quantity integer not null,
  cost_price decimal(10,2) not null,
  note text,
  verified boolean default false,
  verification_date timestamp with time zone,
  batch_id text,
  timestamp bigint
);

alter table packages enable row level security;

create policy "Users can view their own packages"
  on packages for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own packages"
  on packages for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own packages"
  on packages for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own packages"
  on packages for delete
  using ( auth.uid() = user_id );

-- Create goods_list table
create table goods_list (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  name text not null,
  category text,
  unit text
);

alter table goods_list enable row level security;

create policy "Users can view their own goods"
  on goods_list for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own goods"
  on goods_list for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own goods"
  on goods_list for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own goods"
  on goods_list for delete
  using ( auth.uid() = user_id );

-- Create sales_history table
create table sales_history (
  id text primary key,
  user_id uuid references auth.users on delete cascade not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  timestamp text not null,
  customer text,
  items jsonb not null,
  total_amount decimal(10,2) not null,
  total_profit decimal(10,2) not null,
  status text default 'completed',
  note text
);

alter table sales_history enable row level security;

create policy "Users can view their own sales"
  on sales_history for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own sales"
  on sales_history for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own sales"
  on sales_history for update
  using ( auth.uid() = user_id );

-- Create sell_prices table
create table sell_prices (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  goods_name text not null,
  price decimal(10,2) not null,
  constraint unique_user_goods unique (user_id, goods_name)
);

alter table sell_prices enable row level security;

create policy "Users can view their own prices"
  on sell_prices for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own prices"
  on sell_prices for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own prices"
  on sell_prices for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own prices"
  on sell_prices for delete
  using ( auth.uid() = user_id );